[package]
name = "lz4"
license = "MIT"
version = "1.16.131"
authors = [ "Artem V. Navrotskiy <bozaro@buzzsoft.ru>" ]
build = "src/build.rs"
description = "Rust LZ4 bindings library."
repository = "https://github.com/bozaro/lz4-rs"
documentation = "https://bozaro.github.io/lz4-rs/lz4/"

[[bin]]
name = "lz4"
test = false
doc = false

[dependencies]
libc = "0.2.5"

[dev-dependencies]
rand = "0.3.14"
skeptic = "0.4"

[build-dependencies]
gcc = "0.3.21"
skeptic = "0.4"
